version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    hostname: dockerproxy
    environment:
      - TZ=Europe/Amsterdam
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - /config/adguard/conf:/opt/adguardhome/conf
      - /config/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
  adguard-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguard-sync
    hostname: adguard-sync
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/adguard-sync:/config
    ports:
      - 8080:8080
    restart: unless-stopped
