version: '3'

services:
  swag:
    container_name: swag
    hostname: swag
    domainname: ${DOMAIN}
    image: lscr.io/linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=${DOMAIN}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=http
      - EMAIL=${EMAIL}
    volumes:
      - /config/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /config/authelia:/config
    restart: unless-stopped
