version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gravity:
    image: ghcr.io/beryju/gravity:stable
    container_name: gravity
    hostname: gravity
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Amsterdam
      - BOOTSTRAP_ROLES=dns;api;etcd;discovery;monitoring;tsdb
      - INSTANCE_IDENTIFIER=gravity_main
    volumes:
      - /config:/data
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
