version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    ports:
      - 9443:9443
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - /config/adguard/conf:/opt/adguardhome/conf
      - /config/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
