version: '3'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - /config/conf:/opt/adguardhome/conf
      - /config/work:/opt/adguardhome/work
    restart: unless-stopped
