version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:1.7.1 # Assuming 1.7.1 as a recent stable version
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.7.1 # Assuming 0.7.1 as a recent stable version
    container_name: dockerproxy
    hostname: dockerproxy
    environment:
      - TZ=Europe/Amsterdam
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  adguard:
    image: adguard/adguardhome:v0.107.46 # Assuming v0.107.46 as a recent stable version
    container_name: adguard
    hostname: adguard
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    volumes:
      - /config/adguard/conf:/opt/adguardhome/conf
      - /config/adguard/work:/opt/adguardhome/work
    restart: unless-stopped
  adguard-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest # linuxserver.io images are generally well-maintained with 'latest'
    container_name: adguard-sync
    hostname: adguard-sync
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/adguard-sync:/config
    ports:
      - 8080:8080
    restart: unless-stopped
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    environment:
      - TZ=Europe/Amsterdam
      - POSTGRES_DB=${PGDB}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASS}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /config/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    shm_size: 256mb
