---
version: "3"

services:
  minecraft_creative:
    container_name: minecraft_creative
    hostname: minecraft_creative
    image: itzg/minecraft-bedrock-server
    ports:
      - 19132:19132/udp
    volumes:
      - "/config/creative:/data"
    environment:
      - TZ=Europe/Amsterdam
      - EULA=TRUE
      - SERVER_NAME=${CREATIVE}
      - SERVER_PORT=19132
      - LEVEL_NAME=${CREATIVE}
      - LEVEL_TYPE=flat
      - GAMEMODE=creative
      - DIFFICULTY=peaceful
    tty: true
    stdin_open: true
    restart: unless-stopped
  minecraft_survival:
    container_name: minecraft_survival
    hostname: minecraft_survival
    image: itzg/minecraft-bedrock-server
    ports:
      - 19133:19133/udp
    volumes:
      - "/config/survival:/data"
    environment:
      - TZ=Europe/Amsterdam
      - EULA=TRUE
      - SERVER_NAME=${SURVIVAL}
      - SERVER_PORT=19133
      - LEVEL_NAME=${SURVIVAL}
      - LEVEL_SEED=95475027
      - GAMEMODE=survival
      - DIFFICULTY=peaceful
    tty: true
    stdin_open: true
    restart: unless-stopped
  acc:
    container_name: acc
    hostname: acc
    image: gotzl/accservermanager
    ports:
     - 9232:9232/tcp
     - 9231:9231/udp
     - 8000:8000
    volumes:
     - /config/acc/server:/server
     - /config/acc/data:/data
    environment:
     - ALLOWED_HOSTS=["*"]
     - SECRET_KEY=${ACCSECRET}

