---
version: "3"

services:
  minecraft:
    container_name: minecraft
    hostname: minecraft
    image: itzg/minecraft-bedrock-server
    ports:
      - 19132:19132/udp
    volumes:
      - "/config:/data"
    environment:
      - TZ=Europe/Amsterdam
      - EULA=TRUE
    tty: true
    stdin_open: true
    restart: unless-stopped
