version: '3'

services:
  duplicati:
    container_name: duplicati
    hostname: duplicati
    image: docker.io/linuxserver/duplicati:latest
    ports:
      - "8200:8200"
    volumes:
      - /data/config/:/config
      - /data/backup/:/backup
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    privileged: true
