version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:1.7.1 # Assuming 1.7.1 as a recent stable version
    container_name: watchtower
    hostname: watchtower
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped # Added restart policy
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.7.1 # Assuming 0.7.1 as a recent stable version
    container_name: dockerproxy
    hostname: dockerproxy
    environment:
      - TZ=Europe/Amsterdam
      - CONTAINERS=1
      - SERVICES=1
      - TASKS=1
      - POST=0
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.2.0 # Updated to latest stable tag v1.2.0 from GitHub releases
    container_name: homepage
    hostname: homepage
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - /config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  sabnzbd:
    container_name: sabnzbd
    hostname: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest # linuxserver.io images are generally well-maintained with 'latest'
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/sabnzbd/:/config/
      - /config/incomplete:/incomplete-downloads/
      - /config/complete:/downloads/
      - /data/:/data/
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=027
  plex:
    container_name: plex
    hostname: plex
    image: docker.io/plexinc/pms-docker:1.40.0.7998-c29d4c0c8 # Assuming 1.40.0.7998 as a recent stable version
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/plex/:/config/
      - /config/plex/temp/Transcode/:/transcode/
      - /data/:/data/
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
  tautulli:
    container_name: tautulli
    hostname: tautulli
    image: lscr.io/linuxserver/tautulli:latest # linuxserver.io images are generally well-maintained with 'latest'
    ports:
      - "8181:8181/tcp"
    volumes:
      - /config/tautulli/:/config
      - /config/plex/Library/Logs/:/logs:ro
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
  sonarr:
    container_name: sonarr
    hostname: sonarr
    image: lscr.io/linuxserver/sonarr:latest # linuxserver.io images are generally well-maintained with 'latest'
    ports:
      - "8989:8989/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/sonarr/:/config/
      - /data/TV/:/tv/
      - /config/complete:/downloads/
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
  radarr:
    container_name: radarr
    hostname: radarr
    image: lscr.io/linuxserver/radarr:latest # linuxserver.io images are generally well-maintained with 'latest'
    ports:
      - "7878:7878/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/radarr/:/config/
      - /data/Movies/:/movies/
      - /config/complete:/downloads/
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
  bazarr:
    container_name: bazarr
    hostname: bazarr
    image: lscr.io/linuxserver/bazarr:latest # linuxserver.io images are generally well-maintained with 'latest'
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022
    volumes:
      - /config/bazarr/:/config/
      - /data/TV/:/tv/
      - /data/Movies/:/movies/
    ports:
      - 6767:6767
    restart: unless-stopped
